### ISSUE TITLE
BankMixin.on_change_with_bank_account 

### ISSUE THREAD

**Issue by maltalk** [trytonspain/trytond-account_bank#1]
The BankMixin.on_change_with_bank_account fails when not called from account.invoice model.

After this [change](https://github.com/trytonspain/trytond-account_bank/commit/92d9d36b2d67eba2f3735eb5b0f158697ff5a972)  when the method is called from account.move.line or any other model using this mixin raises a KeyError.

`KeyError: 'on_change_with_payment_type_kind'
`
In addition the basic ModelTestCase.test_field_methods raises an error when running the test suite.

**Comment by bernatnan** [comment]
Resolt en el commit #d4cf0e8.
